New asterisk commands
marcelog/elixir_agi pull request #2
Opened 2016-12-05 22:55 UTC by alisinabh

## Asterisk AGI commands implemented:

- CONTROL STREAM FILE
- GET OPTION
- GET DATA
- RECORD FILE
- WAIT FOR DIGIT
- CHANNEL STATUS

### ElixirAgi.Agi.custom_cmd/3 func implemented for calling any other asterisk command outside EXEC command of asterisk
### README.md change: exec/3 ==> custom_cmd/3

## Please replace travis build badge with original repository badge or remove it

2016-12-05 23:18 UTC, marcelog commented
Hey :)

Thanks for the pull. I've made a few comments on the changes.

Also, could you please squash the commits into 1?

Thanks!

2016-12-05 23:49 UTC, alisinabh commented
Hi @marcelog  :)
Thank you very much for your immediate response.

I've squashed commits into 1

but i cant see any comments on code?!

2016-12-05 23:55 UTC, marcelog requested changes

2016-12-05 23:55 UTC, marcelog commented on .travis.yml
> +language: elixir
This doesn't belong to this pull, please open a different pull request if needed.

2016-12-05 23:55 UTC, marcelog commented on README.md
> +[![Build Status](https://travis-ci.org/alisinabh/elixir_agi.svg?branch=master)](https://travis-ci.org/alisinabh/elixir_agi)
This doesn't belong to this pull, please open a different pull request if needed.

2016-12-05 23:55 UTC, marcelog commented on lib/elixir_agi/agi.ex
> +  @spec custom_cmd(t, String.t, []) :: Result.t
Question: What's the point of this new function if run/3 is already there?

2016-12-06 00:00 UTC, marcelog commented
Sorry, I forgot to submit the changes. Can you see them now? Thanks!

2016-12-06 00:14 UTC, alisinabh commented
Yep, resolved!

sorry i thought run/3 is private :))

2016-12-06 00:22 UTC, marcelog approved these changes

2016-12-06 00:26 UTC, marcelog requested changes

2016-12-06 00:26 UTC, marcelog commented on lib/elixir_agi/agi.ex
> +  #TODO: Implement speeck AST commands
There are a lot of other ones to implement, perhaps an open issue or pull request is better than these comments in the code

2016-12-06 00:27 UTC, marcelog commented
Hi @alisinabh!

Thanks for the changes :) I've submitted one more, and when you're done, please squash everything into just 1 commit and I'll merge :)

Best!

2016-12-06 00:31 UTC, alisinabh commented
TODO lines removed!
Squashed and ready B)

by the way, i don't know why are we squashing commits? i'm new to github pulls

2016-12-06 00:37 UTC, marcelog approved these changes

2016-12-06 00:37 UTC, merged

2016-12-06 00:40 UTC, marcelog commented
Thanks for the contribution @alisinabh!

P.S: Squashing is used in this case to make it look more clean.

Cheers!

2016-12-06 00:42 UTC, alisinabh commented
@marcelog thank you very much for your time!

This library is gonna be so useful to me. Looking forward to improve it. 👍 

Great job!

2016-12-06 00:47 UTC, marcelog commented
Great! Thanks for your words, looking forward to merge those improvements :)

All the best!